meal_plans/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from meal_plans.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
)


urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plan_list"),
    path(
        "create/",
        MealPlanCreateView.as_view(),
        name="meal_plan_create",
    ),
    path(
        "<int:pk>/",
        MealPlanDetailView.as_view(),
        name="meal_plan_detail",
    ),
    path(
        "<int:pk>/edit/",
        MealPlanUpdateView.as_view(),
        name="meal_plan_update",
    ),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plan_delete",
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from recipes.views import signup_user

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("meal_plans/", include("meal_plans.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", signup_user, name="signup_user"),
]

tags/urls.py
from django.urls import path

from tags.views import show_tags

urlpatterns = [
    path("", show_tags, name="tags_list"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

# Create your models here.

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

meal_plans/forms.py
from django.forms import ModelForm
from meal_plans.models import MealPlan


class MealPlanForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = ["name", "date", "recipes"]


class MealPlanDeleteForm(ModelForm):
    class Meta:
        model = MealPlan
        fields = []

meal_plans/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from meal_plans.models import MealPlan
from django.urls import reverse_lazy

# Create your views here.


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 7

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("meal_plan_detail", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plan_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %} {% block content %}

<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>

{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %} {% load markdownify %} {% block content %}
<main class="recipe-detail">
  {% if user.id == mealplan.owner_id %}
  <div>
    <p><a href="{% url 'meal_plan_update' mealplan.id %}">Edit Plan</a></p>
    <p><a href="{% url 'meal_plan_delete' mealplan.id %}">Delete Plan</a></p>
  </div>
  <h1>{{ mealplan.name }}</h1>
  <p>{{ mealplan.date }}</p>
  <ul>
    {% for recipe in mealplan.recipes.all %}
    <li>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>Not authorized to view!</p>
  {% endif %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>

{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %} 
{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}
{% block content %} 
<main class="recipe-grid">
    <a href="{% url 'meal_plan_create' %}">Create Meal Plan</a>
    {% for plan in mealplan_list %}
    <div class="recipe-card">
      <h2 class="recipe-card-title">
        <a href="{% url 'meal_plan_detail' plan.pk %}">{{ plan.name }}</a>
      </h2>
      <p>
        <p class="recipe-card-date">{{ plan.date }}</p>
      </p>
    </div>
    {% endfor %}
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %} {% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}